"""
Weekly digest generator – produces Markdown and HTML reports.
"""

from __future__ import annotations

import datetime
import logging
from typing import List

from app.db.models import Bill

logger = logging.getLogger(__name__)

# ── HTML Template ────────────────────────────────────────────────

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Animal Legislation Weekly Digest</title>
<style>
:root {{
    --bg: #0a0a0f;
    --card: #12121a;
    --border: #1e1e2e;
    --text: #e0e0e6;
    --muted: #8888a0;
    --pro: #22c55e;
    --anti: #ef4444;
    --neutral: #6b7280;
    --accent: #a855f7;
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    font-family: 'Segoe UI', sans-serif;
    background: var(--bg);
    color: var(--text);
    padding: 40px 20px;
    line-height: 1.6;
}}
.container {{ max-width: 720px; margin: 0 auto; }}
h1 {{
    font-size: 28px;
    margin-bottom: 8px;
    background: linear-gradient(135deg, var(--accent), #ec4899);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}}
.subtitle {{ color: var(--muted); margin-bottom: 32px; font-size: 14px; }}
.stats {{
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 12px;
    margin-bottom: 32px;
}}
.stat {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 16px;
    text-align: center;
}}
.stat-value {{ font-size: 24px; font-weight: 700; }}
.stat-label {{ font-size: 11px; text-transform: uppercase; color: var(--muted); letter-spacing: 1px; }}
.bill-card {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 20px;
    margin-bottom: 12px;
}}
.bill-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }}
.bill-title {{ font-weight: 600; font-size: 15px; }}
.badge {{
    display: inline-block;
    padding: 3px 10px;
    border-radius: 20px;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
}}
.badge-pro {{ background: rgba(34,197,94,0.15); color: var(--pro); }}
.badge-anti {{ background: rgba(239,68,68,0.15); color: var(--anti); }}
.badge-neutral {{ background: rgba(107,114,128,0.15); color: var(--neutral); }}
.bill-meta {{ font-size: 13px; color: var(--muted); }}
.score-bar {{
    height: 6px;
    background: var(--border);
    border-radius: 3px;
    margin-top: 10px;
    overflow: hidden;
}}
.score-fill {{ height: 100%; border-radius: 3px; background: linear-gradient(90deg, var(--accent), #ec4899); }}
.footer {{ text-align: center; margin-top: 40px; color: var(--muted); font-size: 12px; }}
</style>
</head>
<body>
<div class="container">
    <h1>🐾 Animal Legislation Weekly Digest</h1>
    <p class="subtitle">Week of {week_date} | {total_bills} bills tracked across {num_states} states</p>

    <div class="stats">
        <div class="stat">
            <div class="stat-value">{total_bills}</div>
            <div class="stat-label">Total</div>
        </div>
        <div class="stat">
            <div class="stat-value" style="color: var(--pro)">{pro_count}</div>
            <div class="stat-label">Pro-Animal</div>
        </div>
        <div class="stat">
            <div class="stat-value" style="color: var(--anti)">{anti_count}</div>
            <div class="stat-label">Anti-Animal</div>
        </div>
        <div class="stat">
            <div class="stat-value" style="color: var(--neutral)">{neutral_count}</div>
            <div class="stat-label">Neutral</div>
        </div>
    </div>

    {bill_cards}

    <div class="footer">
        <p>Generated by Animal Legislation Tracker | {generation_time}</p>
    </div>
</div>
</body>
</html>"""


def _badge_class(classification: str) -> str:
    return {
        "PRO": "badge-pro",
        "ANTI": "badge-anti",
        "NEUTRAL": "badge-neutral",
    }.get(classification, "badge-neutral")


def _bill_card_html(bill: Bill) -> str:
    score = bill.score or 0
    sponsors = bill.sponsors or []
    sponsor_names = ", ".join(
        s.get("name", "Unknown") for s in sponsors[:3]
    ) if isinstance(sponsors, list) else str(sponsors)

    return f"""
    <div class="bill-card">
        <div class="bill-header">
            <span class="bill-title">{bill.bill_number} — {bill.state}</span>
            <span class="badge {_badge_class(bill.classification or 'NEUTRAL')}">{bill.classification or 'N/A'}</span>
        </div>
        <div style="margin-bottom: 6px;">{bill.title}</div>
        <div class="bill-meta">
            Sponsor: {sponsor_names} | Committee: {bill.committee or 'N/A'} | Status: {bill.status or 'N/A'}
        </div>
        <div class="score-bar">
            <div class="score-fill" style="width: {min(score, 100)}%"></div>
        </div>
        <div class="bill-meta" style="margin-top: 4px; text-align: right;">Score: {score:.1f}/100</div>
    </div>"""


def generate_html_digest(bills: List[Bill]) -> str:
    """Generate an HTML email-ready digest."""
    now = datetime.datetime.utcnow()
    pro = sum(1 for b in bills if b.classification == "PRO")
    anti = sum(1 for b in bills if b.classification == "ANTI")
    neutral = len(bills) - pro - anti
    states = set(b.state for b in bills)

    # Sort by score descending
    sorted_bills = sorted(bills, key=lambda b: b.score or 0, reverse=True)
    bill_cards = "\n".join(_bill_card_html(b) for b in sorted_bills)

    return HTML_TEMPLATE.format(
        week_date=now.strftime("%B %d, %Y"),
        total_bills=len(bills),
        num_states=len(states),
        pro_count=pro,
        anti_count=anti,
        neutral_count=neutral,
        bill_cards=bill_cards,
        generation_time=now.strftime("%Y-%m-%d %H:%M UTC"),
    )


def generate_markdown_digest(bills: List[Bill]) -> str:
    """Generate a Markdown digest."""
    now = datetime.datetime.utcnow()
    pro = sum(1 for b in bills if b.classification == "PRO")
    anti = sum(1 for b in bills if b.classification == "ANTI")
    neutral = len(bills) - pro - anti
    states = set(b.state for b in bills)

    lines = [
        f"# 🐾 Animal Legislation Weekly Digest",
        f"",
        f"**Week of {now.strftime('%B %d, %Y')}** | {len(bills)} bills across {len(states)} states",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Total Bills | {len(bills)} |",
        f"| 🟢 Pro-Animal | {pro} |",
        f"| 🔴 Anti-Animal | {anti} |",
        f"| ⚪ Neutral | {neutral} |",
        f"",
        f"---",
        f"",
    ]

    # Group by classification
    for cls, emoji, label in [("PRO", "🟢", "Pro-Animal"), ("ANTI", "🔴", "Anti-Animal"), ("NEUTRAL", "⚪", "Neutral")]:
        group = [b for b in bills if b.classification == cls]
        if not group:
            continue
        lines.append(f"## {emoji} {label} Bills ({len(group)})")
        lines.append("")
        for b in sorted(group, key=lambda x: x.score or 0, reverse=True):
            sponsors = b.sponsors or []
            sponsor_str = ", ".join(s.get("name", "?") for s in sponsors[:2]) if isinstance(sponsors, list) else ""
            lines.append(f"### {b.bill_number} ({b.state})")
            lines.append(f"**{b.title}**")
            lines.append(f"- Score: **{b.score or 0:.1f}**/100")
            lines.append(f"- Sponsor: {sponsor_str or 'N/A'}")
            lines.append(f"- Committee: {b.committee or 'N/A'}")
            lines.append(f"- Status: {b.status or 'N/A'}")
            lines.append("")
        lines.append("---")
        lines.append("")

    lines.append(f"*Generated: {now.strftime('%Y-%m-%d %H:%M UTC')}*")
    return "\n".join(lines)
